name: macOS SwiftGit2 Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        xcode: [ Xcode_14.3, Xcode_15.2.0 ]
        os: [ macos-13 ]
        include:
          - xcode: Xcode_15.4
            os: macos-14
          - xcode: Xcode_16.2
            os: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app

      - name: Update libgit2
        run: script/update_libgit2

      - name: Bootstrap
        run: script/bootstrap

      - name: Archive macOS (arm64 + x86_64)
        run: |
          xcodebuild archive \
            -workspace SwiftGit2.xcworkspace \
            -scheme SwiftGit2-OSX \
            -archivePath ./archives/macos \
            -destination 'generic/platform=macOS' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            ARCHS='arm64 x86_64'

      - name: Create XCFramework (macOS only)
        run: |
          xcodebuild -create-xcframework \
            -framework ./archives/macos.xcarchive/Products/Library/Frameworks/SwiftGit2.framework \
            -debug-symbols ./archives/macos.xcarchive/dSYMs/SwiftGit2.framework.dSYM \
            -output SwiftGit2.xcframework

      - name: Zip xcframework
        run: |
          mkdir -p output
          zip -r output/SwiftGit2.xcframework.zip SwiftGit2.xcframework

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwiftGit2-xcframework-macos-${{ matrix.xcode }}
          path: output/SwiftGit2.xcframework.zip

