name: Build SwiftGit2 Framework

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13 ]
        xcode: [ Xcode_14.3 ]
        include:
          - os: macos-14
            xcode: Xcode_15.4
          - os: macos-14
            xcode: Xcode_16.2

    steps:
      - name: List Xcodes
        run: ls /Applications | grep Xcode

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app

      - name: Get Architecture
        run: echo "ARCHITECTURE=$(uname -m)" >> $GITHUB_ENV

      - name: Update Dependencies
        run: |
          ./script/update_libgit2
          ./script/bootstrap

      - name: Build SwiftGit2.framework
        run: |
          xcodebuild archive \
            -scheme SwiftGit2 \
            -archivePath SwiftGit2.xcarchive \
            -destination 'generic/platform=macOS' \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            ENABLE_LIBRARY_EVOLUTION=YES \
            ARCHS="arm64 x86_64" \
            ONLY_ACTIVE_ARCH=NO

      - name: Export Built Framework
        run: |
          mkdir output
          cp -R SwiftGit2.xcarchive/Products/Library/Frameworks/SwiftGit2.framework output/
          cp -R SwiftGit2.xcarchive/dSYMs/SwiftGit2.framework.dSYM output/ || true
          zip -ry output/SwiftGit2.framework.zip output/SwiftGit2.framework

      - name: Upload Framework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwiftGit2-${{ matrix.xcode }}-${{ matrix.os }}
          path: output/SwiftGit2.framework.zip
