name: pull request

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        xcode: [ Xcode_14.3, Xcode_15.2.0 ]
        os: [ macos-13 ]
        include:
          - xcode: Xcode_15.4
            os: macos-14
          - xcode: Xcode_16.2
            os: macos-14

    steps:
      - name: Show available Xcodes
        run: ls -la /Applications/Xcode*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Get architecture
        run: |
          echo "ARCHITECTURE=$(uname -m)" >> $GITHUB_ENV
          echo "Arch: $(uname -m)"

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app

      - name: Show available schemes
        run: xcodebuild -workspace SwiftGit2.xcworkspace -list

      - name: Update libgit2
        run: script/update_libgit2

      - name: Bootstrap
        run: script/bootstrap

      - name: Build macOS framework (universal)
        run: |
          xcodebuild archive \
            -workspace SwiftGit2.xcworkspace \
            -scheme SwiftGit2-OSX \
            -archivePath SwiftGit2.xcarchive \
            -sdk macosx \
            -destination 'platform=macOS' \
            ARCHS="arm64 x86_64" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Zip build artifact
        run: |
          mkdir -p output
          zip -r output/SwiftGit2.xcarchive.zip SwiftGit2.xcarchive

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwiftGit2-${{ matrix.xcode }}-${{ matrix.os }}
          path: output/SwiftGit2.xcarchive.zip
